name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - dev
      - 'releases/*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: docker/login-action@v3
        with:
          registry: registry.jetbrains.team
          username: ${{ secrets.SPACE_USERNAME }}
          password: ${{ secrets.SPACE_PASSWORD }}
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.2
        with:
          args: -l,registry.jetbrains.team/p/sa/containers/qodana-cdnet:2023.3.6420.90.76
